// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: proto/checker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DDNSUpdateResponse_Status int32

const (
	DDNSUpdateResponse_SUCCESS DDNSUpdateResponse_Status = 0
	DDNSUpdateResponse_FAILURE DDNSUpdateResponse_Status = 1
)

// Enum value maps for DDNSUpdateResponse_Status.
var (
	DDNSUpdateResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	DDNSUpdateResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x DDNSUpdateResponse_Status) Enum() *DDNSUpdateResponse_Status {
	p := new(DDNSUpdateResponse_Status)
	*p = x
	return p
}

func (x DDNSUpdateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DDNSUpdateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_checker_proto_enumTypes[0].Descriptor()
}

func (DDNSUpdateResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_checker_proto_enumTypes[0]
}

func (x DDNSUpdateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DDNSUpdateResponse_Status.Descriptor instead.
func (DDNSUpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{1, 0}
}

type GetStatusResponse_Status int32

const (
	GetStatusResponse_SUCCESS GetStatusResponse_Status = 0
	GetStatusResponse_FAILURE GetStatusResponse_Status = 1
)

// Enum value maps for GetStatusResponse_Status.
var (
	GetStatusResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	GetStatusResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x GetStatusResponse_Status) Enum() *GetStatusResponse_Status {
	p := new(GetStatusResponse_Status)
	*p = x
	return p
}

func (x GetStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_checker_proto_enumTypes[1].Descriptor()
}

func (GetStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_checker_proto_enumTypes[1]
}

func (x GetStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStatusResponse_Status.Descriptor instead.
func (GetStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{5, 0}
}

type DDNSUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain    string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *DDNSUpdateRequest) Reset() {
	*x = DDNSUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DDNSUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDNSUpdateRequest) ProtoMessage() {}

func (x *DDNSUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDNSUpdateRequest.ProtoReflect.Descriptor instead.
func (*DDNSUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{0}
}

func (x *DDNSUpdateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DDNSUpdateRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type DDNSUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DDNSUpdateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.DDNSUpdateResponse_Status" json:"status,omitempty"`
}

func (x *DDNSUpdateResponse) Reset() {
	*x = DDNSUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DDNSUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDNSUpdateResponse) ProtoMessage() {}

func (x *DDNSUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDNSUpdateResponse.ProtoReflect.Descriptor instead.
func (*DDNSUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{1}
}

func (x *DDNSUpdateResponse) GetStatus() DDNSUpdateResponse_Status {
	if x != nil {
		return x.Status
	}
	return DDNSUpdateResponse_SUCCESS
}

type GetCurrentIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentIPRequest) Reset() {
	*x = GetCurrentIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIPRequest) ProtoMessage() {}

func (x *GetCurrentIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIPRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{2}
}

type GetCurrentIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpV4 string `protobuf:"bytes,1,opt,name=ip_v4,json=ipV4,proto3" json:"ip_v4,omitempty"`
	IpV6 string `protobuf:"bytes,2,opt,name=ip_v6,json=ipV6,proto3" json:"ip_v6,omitempty"`
}

func (x *GetCurrentIPResponse) Reset() {
	*x = GetCurrentIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentIPResponse) ProtoMessage() {}

func (x *GetCurrentIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentIPResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentIPResponse) GetIpV4() string {
	if x != nil {
		return x.IpV4
	}
	return ""
}

func (x *GetCurrentIPResponse) GetIpV6() string {
	if x != nil {
		return x.IpV6
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status GetStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.GetStatusResponse_Status" json:"status,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_checker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_checker_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetStatus() GetStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetStatusResponse_SUCCESS
}

var File_proto_checker_proto protoreflect.FileDescriptor

var file_proto_checker_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4a, 0x0a, 0x11, 0x44, 0x44, 0x4e,
	0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x6f, 0x0a, 0x12, 0x44, 0x44, 0x4e, 0x53, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x44, 0x4e, 0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49,
	0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x70, 0x5f, 0x76, 0x34, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x56, 0x34, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x70,
	0x5f, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x56, 0x36, 0x22,
	0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x22,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45,
	0x10, 0x01, 0x32, 0xcd, 0x01, 0x0a, 0x0b, 0x44, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x44, 0x4e, 0x53,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x44, 0x4e, 0x53,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x44, 0x4e, 0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x12,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x64, 0x64, 0x6e, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_checker_proto_rawDescOnce sync.Once
	file_proto_checker_proto_rawDescData = file_proto_checker_proto_rawDesc
)

func file_proto_checker_proto_rawDescGZIP() []byte {
	file_proto_checker_proto_rawDescOnce.Do(func() {
		file_proto_checker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_checker_proto_rawDescData)
	})
	return file_proto_checker_proto_rawDescData
}

var file_proto_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_checker_proto_goTypes = []interface{}{
	(DDNSUpdateResponse_Status)(0), // 0: pb.DDNSUpdateResponse.Status
	(GetStatusResponse_Status)(0),  // 1: pb.GetStatusResponse.Status
	(*DDNSUpdateRequest)(nil),      // 2: pb.DDNSUpdateRequest
	(*DDNSUpdateResponse)(nil),     // 3: pb.DDNSUpdateResponse
	(*GetCurrentIPRequest)(nil),    // 4: pb.GetCurrentIPRequest
	(*GetCurrentIPResponse)(nil),   // 5: pb.GetCurrentIPResponse
	(*GetStatusRequest)(nil),       // 6: pb.GetStatusRequest
	(*GetStatusResponse)(nil),      // 7: pb.GetStatusResponse
}
var file_proto_checker_proto_depIdxs = []int32{
	0, // 0: pb.DDNSUpdateResponse.status:type_name -> pb.DDNSUpdateResponse.Status
	1, // 1: pb.GetStatusResponse.status:type_name -> pb.GetStatusResponse.Status
	2, // 2: pb.DDNSService.UpdateDDNSRecord:input_type -> pb.DDNSUpdateRequest
	6, // 3: pb.DDNSService.GetStatus:input_type -> pb.GetStatusRequest
	4, // 4: pb.DDNSService.GetCurrentIP:input_type -> pb.GetCurrentIPRequest
	3, // 5: pb.DDNSService.UpdateDDNSRecord:output_type -> pb.DDNSUpdateResponse
	7, // 6: pb.DDNSService.GetStatus:output_type -> pb.GetStatusResponse
	5, // 7: pb.DDNSService.GetCurrentIP:output_type -> pb.GetCurrentIPResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_checker_proto_init() }
func file_proto_checker_proto_init() {
	if File_proto_checker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_checker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DDNSUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_checker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DDNSUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_checker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_checker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_checker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_checker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_checker_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_checker_proto_goTypes,
		DependencyIndexes: file_proto_checker_proto_depIdxs,
		EnumInfos:         file_proto_checker_proto_enumTypes,
		MessageInfos:      file_proto_checker_proto_msgTypes,
	}.Build()
	File_proto_checker_proto = out.File
	file_proto_checker_proto_rawDesc = nil
	file_proto_checker_proto_goTypes = nil
	file_proto_checker_proto_depIdxs = nil
}
